import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/sections/navBar";




export const metadata: Metadata = {
  title: "Webs de otro planeta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="bg-neutral-950 text-white antialiased">
        <NavBar></NavBar>

        <main>{children}</main>
      </body>
    </html>
  );
}
